class Employee {
  readonly id: number; //this attribute is readonly because it's not modifiable, the id is autogenerated in the DB
  name: string;
  salary: number;
  password: number | string;
  promoted?: boolean;

  constructor(
    id: number,
    name: string,
    salary: number,
    password: number | string,
    promoted?: boolean
  ) {
    this.id = id;
    this.name = name;
    this.salary = salary;
    this.password = password;
    this.promoted = promoted;
  }
}
